### PR TITLE
Dutch2

### PR DESCRIPTION
**Pull request by jdutchfoy**

### CODE REVIEW

**Review by jdutchfoy — COMMENTED** [review]
good

**Review by jdutchfoy — COMMENTED** [review]
all good

**Comment by jdutchfoy** [comment]
good to go

**Review by jamesCodes808 — APPROVED** [review]

**Review by jdutchfoy — COMMENTED** [review]
good

**Review by jdutchfoy — COMMENTED** [review]
good 

function Home() {
  // Your component code here

**Review by jdutchfoy — COMMENTED** [review]
good 

function Home() {
  // Your component code here

**Review by jamesCodes808 — APPROVED** [review]

**Pull request closed without merging**
